POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "The lorem ipsum of life",
    "author": "Me",
    "url": "http://localhost:3003",
    "likes": 1
}

###
DELETE http://localhost:3003/api/blogs/5a422a851b54a676234d17f7

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
    "likes":1
}