POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NDkzMTRhZTgwZGUzNTJmMDFjZWY1NCIsImlhdCI6MTY4MjU5MzY2OH0.8arICmUFDefVzyBzU8f2nQlJ5bbMIZYjAjlub1LQGg8

{
    "title": "Mama Mia !",
    "author": "Mario Bros",
    "url": "http://localhost:3003",
    "likes": 1000
}

###
DELETE http://localhost:3003/api/blogs/644a57aa37d3686f1a8142de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NDkzMTRhZTgwZGUzNTJmMDFjZWY1NCIsImlhdCI6MTY4MjU5MzY2OH0.8arICmUFDefVzyBzU8f2nQlJ5bbMIZYjAjlub1LQGg8

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
    "likes":1
}